### ISSUE TITLE
mssql connector not working

### ISSUE THREAD

**Issue by Sano123456** [debezium/debezium-incubator#37]
when i load the configuration it return me this error
[2018-10-24 12:23:59,209] ERROR Failed to start task mssql-0 (org.apache.kafka.connect.runtime.Worker:455)
org.apache.kafka.common.config.ConfigException: Invalid value io.confluent.connect.cdc.mssql.MsSqlSourceTask for configuration task.class: Class io.confluent.connect.cdc.mssql.MsSqlSourceTask could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:724)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
        at org.apache.kafka.connect.runtime.TaskConfig.<init>(TaskConfig.java:51)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:408)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:873)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:111)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:888)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:884)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

cdc it's another plugin , why is asking me to use it?

let me know
thanks

**Comment by Sano123456** [comment]
This is my configuration file


name=mssql
connector.class=io.debezium.connector.sqlserver.SqlServerConnector
tasks.max=2
initial.database=mydb
database.hostname=...
database.port=1433
database.user=...
database.password=....
database.dbname=test
database.history.kafka.bootstrap.servers=localhost:9092
database.history.kafka.topic=oris_history
table.whitelist=mytable

**Comment by jpechane** [comment]
Could you use Connect API to get the configuartion of the connector as is stored in Connect?
