### ISSUE TITLE
sqlserver connector always throw NullPointerException when restart

### ISSUE THREAD

**Issue by hengheng0haha** [debezium/debezium-incubator#52]
connector version: latest(commit 589bbe1) 
### log:
```
ERROR Unexpected exception while processing record 'ConsumerRecord(topic = db.historyc, partition = 0, offset = 0, CreateTime = 1543999502807, serialized key size = -1, serialized value size = 200, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = {
  "source" : {
    "server" : "fullfillment"
  },
  "position" : {
    "snapshot" : true,
    "snapshot_completed" : true
  },
  "databaseName" : "con2016",
  "schemaName" : "dbo",
  "ddl" : "N/A"
})' (io.debezium.relational.history.KafkaDatabaseHistory:248)
java.lang.NullPointerException
	at io.debezium.relational.history.AbstractDatabaseHistory.lambda$recover$1(AbstractDatabaseHistory.java:92)
	at io.debezium.relational.history.KafkaDatabaseHistory.recoverRecords(KafkaDatabaseHistory.java:238)
	at io.debezium.relational.history.AbstractDatabaseHistory.recover(AbstractDatabaseHistory.java:73)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:43)
	at io.debezium.connector.sqlserver.SqlServerConnectorTask.start(SqlServerConnectorTask.java:107)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:47)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jpechane** [comment]
Thnaks for the report, this is fixed in https://github.com/debezium/debezium-incubator/pull/50

**Comment by hengheng0haha** [comment]
thanks, it work!
