### ISSUE TITLE
no snapshot found based on specified time

### ISSUE THREAD

**Issue by ceyhunkerti** [debezium/debezium-incubator#85]
Hi i've followed  [this](https://debezium.io/docs/connectors/oracle) tutorial.

when i check the connector status with
`http://localhost:8083/connectors/connector-name/status`

I get the below response. And i could'nt figure out the reason

```json
{
  "name": "connector-name",
  "connector": {
    "state": "RUNNING",
    "worker_id": "127.0.1.1:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "FAILED",
      "worker_id": "127.0.1.1:8083",
      "trace": "org.apache.kafka.connect.errors.ConnectException: An exception ocurred in the change event producer. This connector will be stopped.
  at io.debezium.connector.base.ChangeEventQueue.throwProducerFailureIfPresent(ChangeEventQueue.java:170)
  at io.debezium.connector.base.ChangeEventQueue.poll(ChangeEventQueue.java:151)
  at io.debezium.connector.oracle.OracleConnectorTask.poll(OracleConnectorTask.java:109)
  at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
  at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.sql.SQLException: ORA-08180: no snapshot found based on specified time
ORA-06512: at \"SYS.TIMESTAMP_TO_SCN\", line 1

  at io.debezium.relational.HistorizedRelationalSnapshotChangeEventSource.execute(HistorizedRelationalSnapshotChangeEventSource.java:169)
  at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:80)
  ... 5 more
Caused by: java.sql.SQLException: ORA-08180: no snapshot found based on specified time
ORA-06512: at \"SYS.TIMESTAMP_TO_SCN\", line 1

  at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1002)
  at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:898)
  at oracle.jdbc.driver.T2CStatement.executeForDescribe(T2CStatement.java:887)
  at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
  at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
  at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1309)
  at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:422)
  at io.debezium.connector.oracle.OracleSnapshotChangeEventSource.getLatestTableDdlScn(OracleSnapshotChangeEventSource.java:175)
  at io.debezium.connector.oracle.OracleSnapshotChangeEventSource.determineSnapshotOffset(OracleSnapshotChangeEventSource.java:111)
  at io.debezium.relational.HistorizedRelationalSnapshotChangeEventSource.execute(HistorizedRelationalSnapshotChangeEventSource.java:127)
  ... 6 more
"
    }
  ],
  "type": "source"
}
```

**Comment by chris-long-ossg** [comment]
We have also experienced this exception (ORA-08180 / ORA-06512) when attempting to use the Oracle Connector with a real world database.  I believe the cause of the problem is as below:

File src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
Line 165
Method getLatestTableDdlScn

This method runs the SQL "SELECT MAX(TIMESTAMP_TO_SCN(last_ddl_time))".  However the Oracle function TIMESTAMP_TO_SCN fails causing fatal exception if a timestamp from last_ddl_time is older than the available SCNs.

From https://docs.oracle.com/database/121/SQLRF/functions211.htm#SQLRF06326
"The association between an SCN and a timestamp when the SCN is generated is remembered by the database for a limited period of time. This period is the maximum of the auto-tuned undo retention period, if the database runs in the Automatic Undo Management mode, and the retention times of all flashback archives in the database, but no less than 120 hours. The time for the association to become obsolete elapses only when the database is open. An error is returned if the timestamp specified for the argument to TIMESTAMP_TO_SCN is too old."

A mitigation for this problem is to alter the SQL to "SELECT TIMESTAMP_TO_SCN(MAX(last_ddl_time))" so that an attempt to get an SCN is made only for the most recent DDL change.
In addition this query should be wrapped in a try/catch and if the above exception is caught an alternate approach should be taken such as retrieving the most recent SCN.

Nb. This problem did not occur for us when working with the Oracle VirtualBox, I assume because the last_ddl_time values are all very recent and well within the SCN retention window.

**Comment by ceyhunkerti** [comment]
Ok, i've changed a few things and a fresh build from source. So far i' am stuck with the below error now.

```
org.apache.kafka.connect.errors.ConnectException: An exception ocurred in the change event producer. This connector will be stopped.
        at io.debezium.connector.base.ChangeEventQueue.throwProducerFailureIfPresent(ChangeEventQueue.java:170)
        at io.debezium.connector.base.ChangeEventQueue.poll(ChangeEventQueue.java:151)
        at io.debezium.connector.oracle.OracleConnectorTask.poll(OracleConnectorTask.java:109)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: oracle.streams.StreamsException: ORA-01031: insufficient privileges


        at io.debezium.connector.oracle.OracleStreamingChangeEventSource.execute(OracleStreamingChangeEventSource.java:74)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:86)
        ... 5 more
Caused by: oracle.streams.StreamsException: ORA-01031: insufficient privileges


        at oracle.streams.XStreamOut.XStreamOutReceiveLCRCallbackNative(Native Method)
        at oracle.streams.XStreamOut.receiveLCRCallback(XStreamOut.java:465)
        at io.debezium.connector.oracle.OracleStreamingChangeEventSource.execute(OracleStreamingChangeEventSource.java:70)
        ... 6 more
[2019-04-30 17:31:33,845] ERROR WorkerSourceTask{id=ing-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
[2019-04-30 17:31:33,846] INFO Connector has already been stopped (io.debezium.connector.oracle.OracleConnectorTask:136)
[2019-04-30 17:31:33,846] INFO [Producer clientId=producer-4] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1139)
```

**Comment by ceyhunkerti** [comment]
besides; in [docs](https://debezium.io/docs/connectors/oracle/)
under `Example Configuration`
`"database.password" : "xsa",` should be `"database.password" : "xs",` i think.

**Comment by ceyhunkerti** [comment]
Finally managed to get success message from connector
```json
{
  "name": "ing-connector",
  "connector": {
    "state": "RUNNING",
    "worker_id": "127.0.1.1:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "RUNNING",
      "worker_id": "127.0.1.1:8083"
    }
  ],
  "type": "source"
}
```
my config lilke

```json
{
	"table.whitelist": "SYS.*",
	"connector.class" : "io.debezium.connector.oracle.OracleConnector",
	"tasks.max" : "1",
	"database.server.name" : "oracle12",
	"database.hostname" : "localhost",
	"database.port" : "32769",
	"database.user" : "sys as sysdba",
	"database.password" : "oracle",
	"database.dbname" : "ORCLCDB.localdomain",
	"database.pdb.name" : "ORCLPDB1",
	"database.out.server.name" : "xout",
	"database.history.kafka.bootstrap.servers" : "localhost:9092",
	"database.history.kafka.topic": "schema-changes.sys"
}
```

so what is the topic name ? can figure out whether it captures the changes ot not ?

i've tried various combinations of the below command with no success.

`confluent consume SYS.DEMO --from-beginning`

**Comment by jpechane** [comment]
@ceyhunkerti Hi, we do not monitor/use github issues for support cases. Could you please use chat or mailing list for such questions? In your case the topic name should be `oracle12.<schemaname>.<tablename>` as your server name is oracle12. Also you try to monitor `SYS` schema whcih is explictlly fitered out.
